### ISSUE TITLE
Add kiosk mode and set up a kiosk machine

### ISSUE THREAD

**Issue by ezio-melotti** [overthesun/simoc-web#181]
In [kiosk mode](https://en.wikipedia.org/wiki/Kiosk_software):
* the user doesn't have access to  a keyboard, only mouse (and possibly a numpad)
* the user can't leave the browser, access other websites, or applications, or close the browser
* the user will not need to create any account or login/logout
* the kiosk will be offline, and should work without internet access
* the kiosk will have a screensaver with a video, that will disappear once a user interacts with it
* some SIMOC features and menus will be disabled
* SIMOC will be running in a loop, resetting its state after a period of inactivity

TODO (on this repo):
- [x] show the 3D layout by default in the config wizard: #170 
- [x] Add a `ctrl+k` shortcut to enter kiosk mode: #177 
- [x] Update routing and menus in kiosk mode: #178 
- [x] Reset SIMOC state after an inactivity period #182 
- [ ] Test the kiosk mode:
  - [ ] check that it works without keyboard
  - [ ] check all paths/menus
  - [x] check all links (there should be no external links) (see #698)
  - [ ] check all routers to the backend (e.g. `/kill_game`)
- [x] Implement idle-reset on the dashboard
- [x] Add a countdown popup before idle-reset
- [ ] Document kiosk mode
- [ ] Hide SAM preset
- [ ] Update labels to include ECLSS (also for other modes) (see #745)

TODO (on the actual kiosk machine):
- [x] Install Kubuntu 22.04 as OS
- [ ] Install dependencies (some might already be installed)
  - [x] Firefox
  - [ ] xscreensaver
  - [ ] mpv
- [x] Install SIMOC (backend/frontend)
- [ ] Create desktop shortcut and/or autorun [Firefox in kiosk mode](https://support.mozilla.org/en-US/kb/firefox-enterprise-kiosk-mode)
- [ ] Set up video screensaver
  - [ ] Create video and copy it on the machine
  - [ ] Set up [`xscreensaver` to use mpv to run the video as a screensaver](https://www.jwz.org/xscreensaver/faq.html#mpeg)
